spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: postgres
    password: Hazari@786#

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret: ${JWT_SECRET:c3ByaW5nLWp3dC1zZWNyZXQtMzItYnl0ZS1rZXktMTIzNDU2Nzg5MA==}
    access:
      expiration: ${ACCESS_EXPIRATION:15m}
    refresh:
      expiration: ${REFRESH_EXPIRATION:14d}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
